# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.6.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

# Maximum number of concurrent jobs for the project
max_jobs: 1
  
#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: git config --global core.autocrlf input

# clone directory
clone_folder: c:\scopesync

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# scripts that run after cloning repository
install:
  - cmd: cd c:\
  - cmd: git clone --recursive --depth 1 -j8 https://github.com/steinbergmedia/vst3sdk.git
  - cmd: git clone --depth 1 https://github.com/WeAreROLI/JUCE.git -b develop
  - ps: (Get-Content -Path "c:/JUCE/extras/Projucer/JuceLibraryCode/AppConfig.h") | ForEach-Object {$_ -Replace "#define JUCER_ENABLE_GPL_MODE 0", "#define JUCER_ENABLE_GPL_MODE 1"} | Set-Content -Path "c:/JUCE/extras/Projucer/JuceLibraryCode/AppConfig.h"
  - cmd: msbuild c:/JUCE/extras/Projucer/Builds/VisualStudio2017/Projucer.sln /property:Platform=x64
  - cmd: c:\JUCE\extras\Projucer\Builds\VisualStudio2017\x64\Debug\App\Projucer.exe --resave C:\scopesync\Juce\ScopeSyncFX\ScopeSyncFX.jucer
  - cmd: mkdir MS
  - cmd: cd MS
  - ps: Start-FileDownload 'https://aka.ms/vs/15/release/vc_redist.x86.exe'
  - ps: Start-FileDownload 'https://aka.ms/vs/15/release/vc_redist.x64.exe'
  
#---------------------------------#
#       build configuration       #
#---------------------------------#

# scripts to run before build
before_build:

# scripts to run after build
after_build:
  - cmd: set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5"  
  - cmd: cd "c:\scopesync\Setup Script"
  - cmd: iscc ScopeSync.iss

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: msbuild C:\scopesync\Juce\ScopeSyncFX\Builds\VisualStudio2017\ScopeSyncFX.sln /p:Configuration=Release /property:Platform=Win32
  - cmd: msbuild C:\scopesync\Juce\ScopeSyncInstPlugin\Builds\VisualStudio2017\ScopeSyncInstPlugin.sln /t:ScopeSyncInstPlugin_StandalonePlugin /p:Configuration=Release /property:Platform=Win32
  - cmd: msbuild C:\scopesync\Juce\ScopeSyncInstPlugin\Builds\VisualStudio2017\ScopeSyncInstPlugin.sln /t:ScopeSyncInstPlugin_StandalonePlugin /p:Configuration="Release (x64)"" /property:Platform=x64
  - cmd: msbuild C:\scopesync\Juce\ScopeSyncInstPlugin\Builds\VisualStudio2017\ScopeSyncInstPlugin.sln /t:ScopeSyncInstPlugin_VST /p:Configuration=Release /property:Platform=Win32
  - cmd: msbuild C:\scopesync\Juce\ScopeSyncInstPlugin\Builds\VisualStudio2017\ScopeSyncInstPlugin.sln /t:ScopeSyncInstPlugin_VST /p:Configuration="Release (x64)"" /property:Platform=x64
  - cmd: msbuild C:\scopesync\Juce\ScopeSyncEffectPlugin\Builds\VisualStudio2017\ScopeSyncEffectPlugin.sln /t:ScopeSyncEffectPlugin_StandalonePlugin /p:Configuration=Release /property:Platform=Win32
  - cmd: msbuild C:\scopesync\Juce\ScopeSyncEffectPlugin\Builds\VisualStudio2017\ScopeSyncEffectPlugin.sln /t:ScopeSyncEffectPlugin_StandalonePlugin /p:Configuration="Release (x64)"" /property:Platform=x64
  - cmd: msbuild C:\scopesync\Juce\ScopeSyncEffectPlugin\Builds\VisualStudio2017\ScopeSyncEffectPlugin.sln /t:ScopeSyncEffectPlugin_VST /p:Configuration=Release /property:Platform=Win32
  - cmd: msbuild C:\scopesync\Juce\ScopeSyncEffectPlugin\Builds\VisualStudio2017\ScopeSyncEffectPlugin.sln /t:ScopeSyncEffectPlugin_VST /p:Configuration="Release (x64)"" /property:Platform=x64
