/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

namespace BinaryData
{

//================== empty.configuration ==================
static const unsigned char temp_binary_data_0[] =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
"\r\n"
"<configuration>\r\n"
"  <parameters/>\r\n"
"  <mapping>\r\n"
"    <textButtons/>\r\n"
"    <sliders/>\r\n"
"    <labels/>\r\n"
"    <comboBoxes/>\r\n"
"    <tabbedComponents/>\r\n"
"  </mapping>\r\n"
"</configuration>\r\n";

const char* empty_configuration = (const char*) temp_binary_data_0;

//================== loader.layout ==================
static const unsigned char temp_binary_data_1[] =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n"
"<layout>\r\n"
"  <!--Main Component-->\r\n"
"  <component backgroundcolour=\"ff2d3035\" lfid=\"system:default\">\r\n"
"    <bounds x=\"0\" y=\"0\" width=\"674\" height=\"100\" />\r\n"
"    <!--Header Section-->\r\n"
"    <component id=\"header\">\r\n"
"        <bounds relativerectangle=\"right - parent.width, 1, parent.width, top + 40\"></bounds>\r\n"
"        <label lfid=\"system:configname\" name=\"configurationname\" text=\"Current Configuration\">\r\n"
"          <bounds x=\"172\" y=\"11\" width=\"131\" height=\"17\"></bounds>\r\n"
"          <font bold=\"true\" height=\"12\"></font>\r\n"
"        </label>\r\n"
"        <textbutton lfid=\"system:scopesynclogo_button\" name=\"showaboutbox\" id=\"showaboutbox\" text=\"\" tooltip=\"Show About Box\">\r\n"
"          <bounds relativerectangle=\"13, 11, left + 151, top + 21\"></bounds>\r\n"
"        </textbutton>\r\n"
"        <textbutton lfid=\"system:new_config_button\" name=\"newconfiguration\" tooltip=\"New Configuration\">\r\n"
"          <bounds x=\"311\" y=\"9\" width=\"20\" height=\"21\"></bounds>\r\n"
"        </textbutton>\r\n"
"        <textbutton lfid=\"system:load_config_button\" name=\"chooseconfiguration\" tooltip=\"Load Configuration\">\r\n"
"          <bounds x=\"331\" y=\"9\" width=\"21\" height=\"21\"></bounds>\r\n"
"        </textbutton>\r\n"
"        <textbutton lfid=\"system:reload_button\" name=\"reloadconfiguration\" tooltip=\"Reload Current Configuration\">\r\n"
"          <bounds x=\"356\" y=\"9\" width=\"21\" height=\"21\"></bounds>\r\n"
"        </textbutton>\r\n"
"        <textbutton lfid=\"system:showconfigurationmanager_button\" name=\"showconfigurationmanager\" id=\"showconfigurationmanager\" text=\"\" tooltip=\"Open Configuration Manager panel\">\r\n"
"          <bounds x=\"379\" y=\"9\" width=\"21\" height=\"21\"></bounds>\r\n"
"        </textbutton>\r\n"
"        <textbutton lfid=\"system:settings_button\" name=\"showusersettings\" id=\"showusersettings\" text=\"\" tooltip=\"Open User Settings panel\">\r\n"
"          <bounds relativerectangle=\"right - 28, showconfigurationmanager.top, parent.width - 4, top + 21\"></bounds>\r\n"
"        </textbutton>\r\n"
"        <textbutton lfid=\"system:snapshot_button\" name=\"snapshot\" id=\"snapshot\" text=\"\" tooltip=\"Send a snapshot of all current parameter values. Ctrl-click to send snapshot for all ScopeSync instances\">\r\n"
"          <bounds relativerectangle=\"right - 32, showusersettings.top, showusersettings.left - 3, top + 21\"></bounds>\r\n"
"        </textbutton>\r\n"
"        <!--Shows additional buttons in Scope DLL header based on device type setting-->\r\n"
"        <tabbedcomponent displaycontext=\"scope\" name=\"Device Type\" showdropshadow=\"false\">\r\n"
"          <bounds relativerectangle=\"right - 100, 6, snapshot.left - 4, top + 32\"></bounds>\r\n"
"          <tabbar orientation=\"right\" depth=\"0\"></tabbar>\r\n"
"          <tab idx=\"1\" name=\"NOPRESET\">\r\n"
"            <component>\r\n"
"              <!--No Controls-->\r\n"
"            </component>\r\n"
"          </tab>\r\n"
"          <tab idx=\"2\" name=\"PRESET\">\r\n"
"            <component>\r\n"
"              <textbutton lfid=\"system:presets_button\" name=\"PresetList\" tooltip=\"Open Preset Browser\">\r\n"
"                <bounds x=\"81\" y=\"2\" width=\"19\" height=\"21\"></bounds>\r\n"
"              </textbutton>\r\n"
"            </component>\r\n"
"          </tab>\r\n"
"          <tab idx=\"3\" name=\"PRESETFX\">\r\n"
"            <component>\r\n"
"              <textbutton lfid=\"FX_Mono_button\" name=\"MonoEffect\" tooltip=\"Mono (use left input)\">\r\n"
"                <bounds x=\"30\" y=\"3\" width=\"27\" height=\"19\"></bounds>\r\n"
"              </textbutton>\r\n"
"              <textbutton lfid=\"FX_Bypass_button\" name=\"BypassEffect\" tooltip=\"Bypass\">\r\n"
"                <bounds x=\"58\" y=\"2\" width=\"20\" height=\"19\"></bounds>\r\n"
"              </textbutton>\r\n"
"              <textbutton lfid=\"system:presets_button\" name=\"PresetList\" tooltip=\"Open Preset Browser\">\r\n"
"                <bounds x=\"81\" y=\"2\" width=\"19\" height=\"21\"></bounds>\r\n"
"              </textbutton>\r\n"
"            </component>\r\n"
"          </tab>\r\n"
"          <tab idx=\"4\" name=\"BCPRESET\">\r\n"
"            <component>\r\n"
"              <textbutton lfid=\"system:patch_button\" name=\"PatchWindow\" tooltip=\"Open Modular Patch Window\">\r\n"
"                <bounds x=\"50\" y=\"2\" width=\"27\" height=\"21\"></bounds>\r\n"
"              </textbutton>\r\n"
"              <textbutton lfid=\"system:presets_button\" name=\"PresetList\" tooltip=\"Open Preset Browser\">\r\n"
"                <bounds x=\"81\" y=\"2\" width=\"19\" height=\"21\"></bounds>\r\n"
"              </textbutton>\r\n"
"            </component>\r\n"
"          </tab>\r\n"
"          <tab idx=\"5\" name=\"BCPRESETFX\">\r\n"
"            <component>\r\n"
"              <textbutton lfid=\"system:patch_button\" name=\"PatchWindow\" tooltip=\"Open Modular Patch Window\">\r\n"
"                <bounds x=\"0\" y=\"2\" width=\"27\" height=\"21\"></bounds>\r\n"
"              </textbutton>\r\n"
"              <textbutton lfid=\"FX_Mono_button\" name=\"MonoEffect\" tooltip=\"Mono (use left input)\">\r\n"
"                <bounds x=\"30\" y=\"3\" width=\"27\" height=\"19\"></bounds>\r\n"
"              </textbutton>\r\n"
"              <textbutton lfid=\"FX_Bypass_button\" name=\"BypassEffect\" tooltip=\"Bypass\">\r\n"
"                <bounds x=\"58\" y=\"2\" width=\"20\" height=\"19\"></bounds>\r\n"
"              </textbutton>\r\n"
"              <textbutton lfid=\"system:presets_button\" name=\"PresetList\" tooltip=\"Open Preset Browser\">\r\n"
"                <bounds x=\"81\" y=\"2\" width=\"19\" height=\"21\"></bounds>\r\n"
"              </textbutton>\r\n"
"            </component>\r\n"
"          </tab>\r\n"
"        </tabbedcomponent>\r\n"
"      </component>\r\n"
"    <!--Background-->\r\n"
"    <component backgroundcolour=\"55000000\" backgroundimage=\"Skins/B-Control/background.png\">\r\n"
"      <bounds relativerectangle=\"right - parent.width, 41, parent.width, parent.height\" />\r\n"
"    </component>\r\n"
"  </component>\r\n"
"</layout>";

const char* loader_layout = (const char*) temp_binary_data_1;

//================== standardHeaderContent.layout ==================
static const unsigned char temp_binary_data_2[] =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n"
"\r\n"
"  <component id=\"header\">\r\n"
"    <bounds relativerectangle=\"right - parent.width, 1, parent.width, top + 40\"></bounds>\r\n"
"    <label lfid=\"system:configname\" name=\"configurationname\" text=\"Current Configuration\">\r\n"
"      <bounds x=\"172\" y=\"11\" width=\"131\" height=\"17\"></bounds>\r\n"
"      <font bold=\"true\" height=\"12\"></font>\r\n"
"    </label>\r\n"
"    <textbutton lfid=\"system:scopesynclogo_button\" name=\"showaboutbox\" id=\"showaboutbox\" text=\"\" tooltip=\"Show About Box\">\r\n"
"      <bounds relativerectangle=\"13, 11, left + 151, top + 21\"></bounds>\r\n"
"    </textbutton>\r\n"
"    <textbutton lfid=\"system:new_config_button\" name=\"newconfiguration\" tooltip=\"New Configuration\">\r\n"
"      <bounds x=\"311\" y=\"9\" width=\"20\" height=\"21\"></bounds>\r\n"
"    </textbutton>\r\n"
"    <textbutton lfid=\"system:load_config_button\" name=\"chooseconfiguration\" tooltip=\"Load Configuration\">\r\n"
"      <bounds x=\"331\" y=\"9\" width=\"21\" height=\"21\"></bounds>\r\n"
"    </textbutton>\r\n"
"    <textbutton lfid=\"system:reload_button\" name=\"reloadconfiguration\" tooltip=\"Reload Current Configuration\">\r\n"
"      <bounds x=\"356\" y=\"9\" width=\"21\" height=\"21\"></bounds>\r\n"
"    </textbutton>\r\n"
"    <textbutton lfid=\"system:showconfigurationmanager_button\" name=\"showconfigurationmanager\" id=\"showconfigurationmanager\" text=\"\" tooltip=\"Open Configuration Manager panel\">\r\n"
"      <bounds x=\"379\" y=\"9\" width=\"21\" height=\"21\"></bounds>\r\n"
"    </textbutton>\r\n"
"    <textbutton lfid=\"system:settings_button\" name=\"showusersettings\" id=\"showusersettings\" text=\"\" tooltip=\"Open User Settings panel\">\r\n"
"      <bounds relativerectangle=\"right - 28, showconfigurationmanager.top, parent.width - 4, top + 21\"></bounds>\r\n"
"    </textbutton>\r\n"
"    <textbutton lfid=\"system:snapshot_button\" name=\"snapshot\" id=\"snapshot\" text=\"\" tooltip=\"Send a snapshot of all current parameter values. Ctrl-click to send snapshot for all ScopeSync instances\">\r\n"
"      <bounds relativerectangle=\"right - 32, showusersettings.top, showusersettings.left - 3, top + 21\"></bounds>\r\n"
"    </textbutton>\r\n"
"    <!--Shows additional buttons in Scope DLL header based on device type setting-->\r\n"
"    <tabbedcomponent displaycontext=\"scope\" name=\"Device Type\" showdropshadow=\"false\">\r\n"
"      <bounds relativerectangle=\"right - 100, 6, snapshot.left - 4, top + 32\"></bounds>\r\n"
"      <tabbar orientation=\"right\" depth=\"0\"></tabbar>\r\n"
"      <tab idx=\"1\" name=\"NOPRESET\">\r\n"
"        <component>\r\n"
"          <!--No Controls-->\r\n"
"        </component>\r\n"
"      </tab>\r\n"
"      <tab idx=\"2\" name=\"PRESET\">\r\n"
"        <component>\r\n"
"          <textbutton lfid=\"system:presets_button\" name=\"PresetList\" tooltip=\"Open Preset Browser\">\r\n"
"            <bounds x=\"81\" y=\"2\" width=\"19\" height=\"21\"></bounds>\r\n"
"          </textbutton>\r\n"
"        </component>\r\n"
"      </tab>\r\n"
"      <tab idx=\"3\" name=\"PRESETFX\">\r\n"
"        <component>\r\n"
"          <textbutton lfid=\"FX_Mono_button\" name=\"MonoEffect\" tooltip=\"Mono (use left input)\">\r\n"
"            <bounds x=\"30\" y=\"3\" width=\"27\" height=\"19\"></bounds>\r\n"
"          </textbutton>\r\n"
"          <textbutton lfid=\"FX_Bypass_button\" name=\"BypassEffect\" tooltip=\"Bypass\">\r\n"
"            <bounds x=\"58\" y=\"2\" width=\"20\" height=\"19\"></bounds>\r\n"
"          </textbutton>\r\n"
"          <textbutton lfid=\"system:presets_button\" name=\"PresetList\" tooltip=\"Open Preset Browser\">\r\n"
"            <bounds x=\"81\" y=\"2\" width=\"19\" height=\"21\"></bounds>\r\n"
"          </textbutton>\r\n"
"        </component>\r\n"
"      </tab>\r\n"
"      <tab idx=\"4\" name=\"BCPRESET\">\r\n"
"        <component>\r\n"
"          <textbutton lfid=\"system:patch_button\" name=\"PatchWindow\" tooltip=\"Open Modular Patch Window\">\r\n"
"            <bounds x=\"50\" y=\"2\" width=\"27\" height=\"21\"></bounds>\r\n"
"          </textbutton>\r\n"
"          <textbutton lfid=\"system:presets_button\" name=\"PresetList\" tooltip=\"Open Preset Browser\">\r\n"
"            <bounds x=\"81\" y=\"2\" width=\"19\" height=\"21\"></bounds>\r\n"
"          </textbutton>\r\n"
"        </component>\r\n"
"      </tab>\r\n"
"      <tab idx=\"5\" name=\"BCPRESETFX\">\r\n"
"        <component>\r\n"
"          <textbutton lfid=\"system:patch_button\" name=\"PatchWindow\" tooltip=\"Open Modular Patch Window\">\r\n"
"            <bounds x=\"0\" y=\"2\" width=\"27\" height=\"21\"></bounds>\r\n"
"          </textbutton>\r\n"
"          <textbutton lfid=\"FX_Mono_button\" name=\"MonoEffect\" tooltip=\"Mono (use left input)\">\r\n"
"            <bounds x=\"30\" y=\"3\" width=\"27\" height=\"19\"></bounds>\r\n"
"          </textbutton>\r\n"
"          <textbutton lfid=\"FX_Bypass_button\" name=\"BypassEffect\" tooltip=\"Bypass\">\r\n"
"            <bounds x=\"58\" y=\"2\" width=\"20\" height=\"19\"></bounds>\r\n"
"          </textbutton>\r\n"
"          <textbutton lfid=\"system:presets_button\" name=\"PresetList\" tooltip=\"Open Preset Browser\">\r\n"
"            <bounds x=\"81\" y=\"2\" width=\"19\" height=\"21\"></bounds>\r\n"
"          </textbutton>\r\n"
"        </component>\r\n"
"      </tab>\r\n"
"    </tabbedcomponent>\r\n"
"  </component>";

const char* standardHeaderContent_layout = (const char*) temp_binary_data_2;

//================== standardSliderLnFs.layout ==================
static const unsigned char temp_binary_data_3[] =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n"
"\r\n"
"<lookandfeels>\r\n"
"  <lookandfeel id=\"JUCE knob\">\r\n"
"    <colours>\r\n"
"      <slider backgroundcolourid=\"ffb8bbbf\" thumbcolourid=\"ffffffff\" trackcolourid=\"ff0000ff\" rotarysliderfillcolourid=\"ff0084ff\" rotaryslideroutlinecolourid=\"ff212121\" textboxbackgroundcolourid=\"00b8bbbf\" textboxoutlinecolourid=\"00fffff"
"f\" textboxtextcolourid=\"ff000000\" textboxhighlightcolourid=\"ff2d3035\"></slider>\r\n"
"      <texteditor backgroundcolourid=\"ffffffff\" textcolourid=\"ffffffff\" highlightcolourid=\"ff2d3035\" highlightedtextcolourid=\"ffffffff\" outlinecolourid=\"7f000000\" focusedoutlinecolourid=\"7f2d3035\" shadowcolourid=\"ff000000\"></texteditor>"
"\r\n"
"    </colours>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1A - White with LED surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Surround.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/surround_knob_line.png\">\r\n"
"          <image filename=\"gfx/Knob1a_white.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1A - Black with LED surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Surround.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/surround_knob_line.png\">\r\n"
"          <image filename=\"gfx/Knob1a_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1B - White with bipolar LED surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Surround.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/surround_knob_line.png\">\r\n"
"          <image filename=\"gfx/Knob1b_white.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1B - Black with bipolar LED surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Surround.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/surround_knob_line.png\">\r\n"
"          <image filename=\"gfx/Knob1b_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1C - White with dotted surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/dotted_surround.png\">\r\n"
"          <image filename=\"gfx/Knob1c_white.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1C - White with lined surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/lined_surround1.png\">\r\n"
"          <image filename=\"gfx/Knob1c_white.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1C - White with numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround1.png\">\r\n"
"          <image filename=\"gfx/Knob1c_white.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1C - White with alt numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround3.png\">\r\n"
"          <image filename=\"gfx/Knob1c_white.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1C - White with Bipolar surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/Bipolar-surround1.png\">\r\n"
"          <image filename=\"gfx/Knob1c_white.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1C - Black with dotted surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/dotted_surround.png\">\r\n"
"          <image filename=\"gfx/Knob1c_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1C - Black with lined surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/lined_surround1.png\">\r\n"
"          <image filename=\"gfx/Knob1c_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1C - Black with numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround1.png\">\r\n"
"          <image filename=\"gfx/Knob1c_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1C - Black with alt numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround3.png\">\r\n"
"          <image filename=\"gfx/Knob1c_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1C - Black with Bipolar surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/Bipolar-surround1.png\">\r\n"
"          <image filename=\"gfx/Knob1c_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1D - White with dotted surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/dotted_surround.png\">\r\n"
"          <image filename=\"gfx/Knob1d_white.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1D - White with lined surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/lined_surround1.png\">\r\n"
"          <image filename=\"gfx/Knob1d_white.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1D - White with numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround1.png\">\r\n"
"          <image filename=\"gfx/Knob1d_white.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1D - White with alt numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround3.png\">\r\n"
"          <image filename=\"gfx/Knob1d_white.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1D - White with Bipolar surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/Bipolar-surround1.png\">\r\n"
"          <image filename=\"gfx/Knob1d_white.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1D - Black with dotted surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/dotted_surround.png\">\r\n"
"          <image filename=\"gfx/Knob1d_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1D - Black with lined surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/lined_surround1.png\">\r\n"
"          <image filename=\"gfx/Knob1d_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1D - Black with numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround1.png\">\r\n"
"          <image filename=\"gfx/Knob1d_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1D - Black with alt numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround3.png\">\r\n"
"          <image filename=\"gfx/Knob1d_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1D - Black with Bipolar surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/Bipolar-surround1.png\">\r\n"
"          <image filename=\"gfx/Knob1d_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1E - Black with dotted surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/dotted_surround.png\">\r\n"
"          <image filename=\"gfx/Knob1e_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1E - Black with lined surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/lined_surround1.png\">\r\n"
"          <image filename=\"gfx/Knob1e_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1E - Black with numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround1.png\">\r\n"
"          <image filename=\"gfx/Knob1e_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1E - Black with alt numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround3.png\">\r\n"
"          <image filename=\"gfx/Knob1e_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 1E - Black with Bipolar surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/Bipolar-surround1.png\">\r\n"
"          <image filename=\"gfx/Knob1e_black.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 2A - Large Black knob with Coloured Cap\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"\">\r\n"
"          <image filename=\"gfx/Knob2a_matte.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <colours>\r\n"
"      <label textcolourid=\"fffa56c9\"></label>\r\n"
"    </colours>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 2B - Large Black knob with Metallic Cap\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"\">\r\n"
"          <image filename=\"gfx/Knob2b_metallic.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <colours>\r\n"
"      <label textcolourid=\"fffa56c9\"></label>\r\n"
"    </colours>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 3A - Small Black knob with dotted surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/dotted_surround.png\">\r\n"
"          <image filename=\"gfx/Knob3a_matte.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 3A - Small Black knob with lined surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/lined_surround1.png\">\r\n"
"          <image filename=\"gfx/Knob3a_matte.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 3A - Small Black knob with numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround2.png\">\r\n"
"          <image filename=\"gfx/Knob3a_matte.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 3A - Small Black knob with alt numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround4.png\">\r\n"
"          <image filename=\"gfx/Knob3a_matte.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 3A - Small Black knob with Bipolar surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/Bipolar-surround1.png\">\r\n"
"          <image filename=\"gfx/Knob3a_matte.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 3B - Small Black knob with dotted surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/dotted_surround.png\">\r\n"
"          <image filename=\"gfx/Knob3b_metallic.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 3B - Small Black knob with lined surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/lined_surround1.png\">\r\n"
"          <image filename=\"gfx/Knob3b_metallic.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 3B - Small Black knob with numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround2.png\">\r\n"
"          <image filename=\"gfx/Knob3b_metallic.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 3B - Small Black knob with alt numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround4.png\">\r\n"
"          <image filename=\"gfx/Knob3b_metallic.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 3B - Small Black knob with Bipolar surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/Bipolar-surround1.png\">\r\n"
"          <image filename=\"gfx/Knob3b_metallic.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 4 - Black knob with dotted surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/dotted_surround.png\">\r\n"
"          <image filename=\"gfx/Knob4.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 4 - Black knob with lined surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/lined_surround1.png\">\r\n"
"          <image filename=\"gfx/Knob4.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 4 - Black knob with numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround1.png\">\r\n"
"          <image filename=\"gfx/Knob4.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 4 - Black knob with alt numbered surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/numbered_surround3.png\">\r\n"
"          <image filename=\"gfx/Knob4.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"Knob 4 - Black knob with Bipolar surround\" parentid=\"JUCE knob\">\r\n"
"    <images>\r\n"
"      <slider>\r\n"
"        <rotary fillbackgroundfilename=\"gfx/Knob1_Cap.png\" backgrounduselnfcolours=\"true\" outlinebackgroundfilename=\"gfx/Bipolar-surround1.png\">\r\n"
"          <image filename=\"gfx/Knob4.png\" numframes=\"63\" ishorizontal=\"false\" />\r\n"
"        </rotary>\r\n"
"      </slider>\r\n"
"    </images>\r\n"
"    <appliesto componenttype=\"slider\" />\r\n"
"  </lookandfeel>\r\n"
"</lookandfeels>";

const char* standardSliderLnFs_layout = (const char*) temp_binary_data_3;

//================== system.lookandfeels ==================
static const unsigned char temp_binary_data_4[] =
"\xef\xbb\xbf<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n"
"<lookandfeels>\r\n"
"  <lookandfeel id=\"system:default\">\r\n"
"    <appliesto componenttype=\"none\" />\r\n"
"    <colours>\r\n"
"      <slider textboxbackgroundcolourid=\"ff000000\" textboxoutlinecolourid=\"ff121517\" textboxtextcolourid=\"ffb3bbbd\" textboxhighlightcolourid=\"ffa7aaae\" thumbcolourid=\"00ffffff\" backgroundcolourid=\"ff000000\"></slider>\r\n"
"      <label textcolourid=\"ff323739\"></label>\r\n"
"      <texteditor focusedoutlinecolourid=\"002f353a\"></texteditor>\r\n"
"      <tabbedcomponent outlinecolourid=\"00000000\"></tabbedcomponent>\r\n"
"      <tabbar tabtextcolourid=\"ffc3cace\" fronttextcolourid=\"ffff7f00\" taboutlinecolourid=\"00000000\"></tabbar>\r\n"
"      <textbutton textcolouroffid=\"00ffffff\" textcolouronid=\"00ff0000\" buttoncolourid=\"ffff0000\"></textbutton>\r\n"
"    </colours>\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"system:load_config_button\" parentid=\"system:default\">\r\n"
"    <appliesto componenttype=\"none\" />\r\n"
"    <images>\r\n"
"      <textbutton upfilename=\"loadConfigButtonOff\" downfilename=\"loadConfigButtonOn\" mouseoverupfilename=\"loadConfigButtonOver\" mouseoverdownfilename=\"loadConfigButtonOn\"></textbutton>\r\n"
"    </images>\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"system:new_config_button\" parentid=\"system:default\">\r\n"
"    <appliesto componenttype=\"none\" />\r\n"
"    <images>\r\n"
"      <textbutton upfilename=\"newConfigOff\" downfilename=\"newConfigOn\" mouseoverupfilename=\"newConfigOver\" mouseoverdownfilename=\"newConfigOn\"></textbutton>\r\n"
"    </images>\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"system:reload_button\" parentid=\"system:default\">\r\n"
"    <appliesto componenttype=\"none\" />\r\n"
"    <images>\r\n"
"      <textbutton upfilename=\"reloadButtonOff\" downfilename=\"reloadButtonOn\" mouseoverupfilename=\"reloadButtonOver\" mouseoverdownfilename=\"reloadButtonOn\"></textbutton>\r\n"
"    </images>\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"system:remove_config_button\" parentid=\"system:default\">\r\n"
"    <appliesto componenttype=\"none\" />\r\n"
"    <images>\r\n"
"      <textbutton upfilename=\"removeConfigButtonOff\" downfilename=\"removeConfigButtonOn\" mouseoverupfilename=\"removeConfigButtonOver\" mouseoverdownfilename=\"removeConfigButtonOn\"></textbutton>\r\n"
"    </images>\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"system:patch_button\" parentid=\"system:default\">\r\n"
"    <appliesto componenttype=\"none\" />\r\n"
"    <images>\r\n"
"      <textbutton upfilename=\"patchWindowButtonOff\" downfilename=\"patchWindowButtonOn\" mouseoverupfilename=\"patchWindowButtonOver\" mouseoverdownfilename=\"patchWindowButtonOn\"></textbutton>\r\n"
"    </images>\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"system:presets_button\" parentid=\"system:default\">\r\n"
"    <appliesto componenttype=\"none\" />\r\n"
"    <images>\r\n"
"      <textbutton upfilename=\"presetsButtonOff\" downfilename=\"presetsButtonOn\" mouseoverupfilename=\"presetsButtonOver\" mouseoverdownfilename=\"presetsButtonOn\"></textbutton>\r\n"
"    </images>\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"system:settings_button\" parentid=\"system:default\">\r\n"
"    <appliesto componenttype=\"none\" />\r\n"
"    <images>\r\n"
"      <textbutton upfilename=\"settingsButtonOff\" downfilename=\"settingsButtonOn\" mouseoverupfilename=\"settingsButtonOver\" mouseoverdownfilename=\"settingsButtonOn\"></textbutton>\r\n"
"    </images>\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"system:snapshot_button\" parentid=\"system:default\">\r\n"
"    <appliesto componenttype=\"none\" />\r\n"
"    <images>\r\n"
"      <textbutton upfilename=\"snapshotOff\" downfilename=\"snapshotOn\" mouseoverupfilename=\"snapshotOver\" mouseoverdownfilename=\"snapshotOn\"></textbutton>\r\n"
"    </images>\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"system:showconfigurationmanager_button\" parentid=\"system:default\">\r\n"
"    <appliesto componenttype=\"none\" />\r\n"
"    <images>\r\n"
"      <textbutton upfilename=\"showconfigurationmanagerOff\" downfilename=\"showconfigurationmanagerOn\" mouseoverupfilename=\"showconfigurationmanagerOver\" mouseoverdownfilename=\"showconfigurationmanagerOn\"></textbutton>\r\n"
"    </images>\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"system:scopesynclogo_button\" parentid=\"system:default\">\r\n"
"    <appliesto componenttype=\"none\" />\r\n"
"    <images>\r\n"
"      <textbutton upfilename=\"scopeSyncLogoOff\" downfilename=\"scopeSyncLogoOn\" mouseoverupfilename=\"scopeSyncLogoOn\" mouseoverdownfilename=\"scopeSyncLogoOn\"></textbutton>\r\n"
"    </images>\r\n"
"  </lookandfeel>\r\n"
"  <lookandfeel id=\"system:configname\">\r\n"
"    <appliesto componenttype=\"none\" />\r\n"
"    <colours>\r\n"
"      <label textcolourid=\"90ffffff\" outlinecolourid=\"90ffffff\"></label>\r\n"
"    </colours>\r\n"
"  </lookandfeel>\r\n"
"</lookandfeels>\r\n";

const char* system_lookandfeels = (const char*) temp_binary_data_4;


const char* getNamedResource (const char*, int&) throw();
const char* getNamedResource (const char* resourceNameUTF8, int& numBytes) throw()
{
    unsigned int hash = 0;
    if (resourceNameUTF8 != 0)
        while (*resourceNameUTF8 != 0)
            hash = 31 * hash + (unsigned int) *resourceNameUTF8++;

    switch (hash)
    {
        case 0x13f60184:  numBytes = 216; return empty_configuration;
        case 0xed361cd6:  numBytes = 5538; return loader_layout;
        case 0x2695bffa:  numBytes = 4772; return standardHeaderContent_layout;
        case 0x383dda9c:  numBytes = 22039; return standardSliderLnFs_layout;
        case 0x5ac2d7c5:  numBytes = 4429; return system_lookandfeels;
        default: break;
    }

    numBytes = 0;
    return 0;
}

const char* namedResourceList[] =
{
    "empty_configuration",
    "loader_layout",
    "standardHeaderContent_layout",
    "standardSliderLnFs_layout",
    "system_lookandfeels"
};

}
